# Generated by Django 3.1.12 on 2025-02-25 13:39

import apps.home.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('prix', models.CharField(max_length=50)),
                ('promotion', models.CharField(blank=True, max_length=10)),
                ('categorie', models.CharField(max_length=50)),
                ('sous_categorie', models.CharField(max_length=50)),
                ('site_web', models.CharField(max_length=50)),
                ('date_extraction', models.DateTimeField()),
                ('caracteristiques', djongo.models.fields.EmbeddedField(model_container=apps.home.models.CaracteristiquesLaptop)),
                ('image_url', models.URLField()),
                ('disponibilite', models.CharField(max_length=50)),
                ('delai_de_livraison', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('prix', models.CharField(max_length=50)),
                ('promotion', models.CharField(blank=True, max_length=10)),
                ('categorie', models.CharField(max_length=50)),
                ('sous_categorie', models.CharField(max_length=50)),
                ('date_extraction', models.DateTimeField()),
                ('caracteristiques', djongo.models.fields.EmbeddedField(model_container=apps.home.models.CaracteristiquesSmartphone)),
                ('image_url', models.URLField()),
                ('disponibilite', models.CharField(max_length=50)),
                ('delai_de_livraison', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
