# Generated by Django 3.1.12 on 2025-02-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smartphone',
            table='smartphone',
        ),
    ]
